### ISSUE TITLE
fluent-plugin-map

### ISSUE THREAD

**Issue by tomity** [fluent-plugins-nursery/contact#1]
## Your repository URL of Fluent plugin

https://github.com/tomity/fluent-plugin-map

## Do you want to add you to this organization?

Yes

## Any question/concern?

煮るなり焼くなり好きにしてください

**Comment by cosmo0920** [comment]
Thanks for interest this organization!
I've already forked your fluent-plugin-map repository.
Please transfer your fluent plugin repository ownership to @okkez?
He will add you this organization and transfer your repository here.

**Comment by okkez** [comment]
@tomity I've invited you this organization. Could you approve the invitation?
And then you can transfer ownership of your project (fluent-plugin-map) to this organization.

See also https://github.com/fluent-plugins-nursery/contact

**Comment by okkez** [comment]
If you want to contact us in Japanese visit https://gitter.im/fluent-plugins-nursery/Lobby, please :bow:

**Comment by tomity** [comment]
approve the invitation: done
transfer ownership: done
add gem owner: done

**Comment by okkez** [comment]
Thanks! I've confirmed.
Done :tada:
