### ISSUE TITLE
 fluent-plugin-remote_syslog

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/contact#15]
This is the ticket to track the transfer process of fluent-plugin-remote_syslog.

## The repository URL of Fluent plugin

https://github.com/dlackty/fluent-plugin-remote_syslog

## Checklist

1. [x] Original author agrees to transfer their project.
   * See https://github.com/dlackty/fluent-plugin-remote_syslog/issues/47 for previous discussions
2. [x] Admins invites the original author to `fluent-plugins-nursery`.
3. [x] Original author transfers the ownership.
   - Transfer repository to `fluent-plugins-nursery`.
   - Add a new maintainer as a Gem owner.
4. [x] Close this ticket.

**Comment by fujimotos** [comment]
> [x] Admins invites the original author to fluent-plugins-nursery.

Invitation sent. This should allow @dlackty to create a repository on this organization
(and hence transfer the ownership of the repostiory).

**Comment by dlackty** [comment]
@fujimotos Transferred. Please have a look.

**Comment by daipom** [comment]
@dlackty Thank you so much! I will check.

**Comment by daipom** [comment]
@dlackty
I have confirmed that the transfer has been completed.
Thank you so much!

Next, could you add me (`fukuda@clear-code.com`) as a Ruby gem owner?
You can use the following command.

`$ gem owner fluent-plugin-remote_syslog --add fukuda@clear-code.com`

**Comment by dlackty** [comment]
@daipom Done adding you as a Ruby gem owner. Please check.

**Comment by daipom** [comment]
@dlackty
I have confirmed it!
This completes all the processes.

We appreciate your kindness! Thank you so much.

Please feel free to contact us anytime!
