### ISSUE TITLE
fluent-plugin-elapsed-time

### ISSUE THREAD

**Issue by sonots** [fluent-plugins-nursery/contact#19]
## The repository URL of your Fluent plugin

https://github.com/sonots/fluent-plugin-elapsed-time

## Do you want us to add you to this GitHub organization?

Yes

## Checklist

- [x] Original author agrees to transfer their project.
- [x] Admins invite the original author to `fluent-plugin-nursery`.
- [x] Original author transfers repository to `fluent-plugins-nursery`. ([How to transfer your repository](../blob/master/README.md#how-to-transfer-your-repository))
- [x] Original author adds a new maintainer as a Gem owner. ([How to add a new maintainer to your Gem](../blob/master/README.md#how-to-add-a-new-maintainer-to-your-gem))
- [x] Close ticket. Done!

**Comment by daipom** [comment]
@sonots Thanks for creating issues!
I just invited you to `fluent-plugin-nursery`.

**Comment by daipom** [comment]
@sonots 
If you are able to join `fluent-plugin-nursery`, please transfer the repositories and add `fukuda@clear-code.com` to the gem owners.
I will update the checklist when I confirm it.

**Comment by sonots** [comment]
@daipom `fluent-plugins-nursery` currectly? Also, I did not have permission to transfer to it.

**Comment by sonots** [comment]
I got you. I accepted invitation.

**Comment by daipom** [comment]
> @daipom `fluent-plugins-nursery` currectly? Also, I did not have permission to transfer to it.

Oh, sorry. This is a typo. 
Yes, `fluent-plugins-nursery` is correct.

> I got you. I accepted invitation.

Now I can confirm many of the repositories are transferred.
Thanks! I'm confirming.

**Comment by sonots** [comment]
All done!

**Comment by daipom** [comment]
Thanks so much!
From here, I will confirm each repository.
If something comes up, please let me contact you again.
Thanks so much!

**Comment by daipom** [comment]
Thanks for transferring!
