### ISSUE TITLE
fluent-plugin-irc

### ISSUE THREAD

**Issue by choplin** [fluent-plugins-nursery/contact#2]
## Your repository URL of Fluent plugin

https://github.com/choplin/fluent-plugin-irc

## Do you want to add you to this organization?

Yes (or add me to collaborators of this plugin)

## Any question/concern?

No

**Comment by okkez** [comment]
@choplin Invited.
Could you accept the invitation and transfer ownership?

**Comment by okkez** [comment]
@choplin Could you add me to owner of https://rubygems.org/gems/fluent-plugin-irc?

```
$ gem owner fluent-plugin-irc -a okkez000@gmail.com
```

**Comment by choplin** [comment]
Sorry for being late. I've added you to the owner via https://github.com/fluent-plugins-nursery/fluent-plugin-irc/pull/17

**Comment by okkez** [comment]
Thanks!
