### ISSUE TITLE
fluent-plugin-stats-notifier

### ISSUE THREAD

**Issue by sonots** [fluent-plugins-nursery/contact#27]
## The repository URL of your Fluent plugin

https://github.com/sonots/fluent-plugin-stats-notifier

## Do you want us to add you to this GitHub organization?

Yes

## Checklist

- [x] Original author agrees to transfer their project.
- [x] Admins invite the original author to `fluent-plugin-nursery`.
- [x] Original author transfers repository to `fluent-plugins-nursery`. ([How to transfer your repository](../blob/master/README.md#how-to-transfer-your-repository))
- [x] Original author adds a new maintainer as a Gem owner. ([How to add a new maintainer to your Gem](../blob/master/README.md#how-to-add-a-new-maintainer-to-your-gem))
- [x] Close ticket. Done!

**Comment by daipom** [comment]
Thanks for transferring!
