### ISSUE TITLE
fluent-plugin-hipchat

### ISSUE THREAD

**Issue by hotchpotch** [fluent-plugins-nursery/contact#3]
fluent-plugin-hipchat

## URL

- https://github.com/hotchpotch/fluent-plugin-hipchat

## Do you want to add you to this organization?

No

## Any question/concern?

This project is good!

**Comment by okkez** [comment]
@hotchpotch Thank you for creating issue to contact us!
I've invited you to this organization.
Could you transfer ownership and leave the team (If you want to leave this organization).

Could you add me to authors of https://rubygems.org/gems/fluent-plugin-hipchat ?

```
$ gem owner fluent-plugin-hipchat -a okkez000@gmail.com
```

**Comment by okkez** [comment]
Thanks! I've confirmed repository and gem authors.

**Comment by hotchpotch** [comment]
@okkez 
Thanks !!
