### ISSUE TITLE
fluent-plugin-systemd

### ISSUE THREAD

**Issue by errm** [fluent-plugins-nursery/contact#32]
## The repository URL of your Fluent plugin

https://github.com/fluent-plugin-systemd/fluent-plugin-systemd

## Do you want us to add you to this GitHub organization?

Yes

## Checklist

- [x] Original author agrees to transfer their project.
- [x] Admins invite the original author to `fluent-plugins-nursery`.
- [x] Original author transfers repository to `fluent-plugins-nursery`. ([How to transfer your repository](../blob/master/README.md#how-to-transfer-your-repository))
- [x] Original author adds a new maintainer as a Gem owner. ([How to add a new maintainer to your Gem](../blob/master/README.md#how-to-add-a-new-maintainer-to-your-gem))
- [x] Close ticket. Done!

**Comment by daipom** [comment]
Thanks @errm!
Invitation sent. Please confirm it.
After joining `fluent-plugins-nursery`, please transfer the repository.
If you have any questions, please let us know here!

**Comment by ashie** [comment]
ping @errm

**Comment by errm** [comment]
OK repo is transfered ...

❓ Should I add all of the people listed as admins [here](https://github.com/fluent-plugins-nursery/contact/blob/master/README.md#admins-alphabetical-order) as rubygems admins for the gem?

**Comment by ashie** [comment]
Thanks transferring the repository!

> ❓ Should I add all of the people listed as admins [here](https://github.com/fluent-plugins-nursery/contact/blob/master/README.md#admins-alphabetical-order) as rubygems admins for the gem?

Need only 1 people.
Remaining member will be added by him.

**Comment by daipom** [comment]
Thanks!
Could you add me (`fukuda@clear-code.com`)?

**Comment by errm** [comment]
No problem ... invite sent!

**Comment by errm** [comment]
🎉

**Comment by daipom** [comment]
I have confirmed it! Thanks!

This completes all the processes.
We appreciate your kindness! Thank you so much!

Please feel free to contact us anytime!
