### ISSUE TITLE
fluent-plugin-cloudwatch-logs

### ISSUE THREAD

**Issue by ryotarai** [fluent-plugins-nursery/contact#4]
Please input your Fluent plugin name to title.

## Your repository URL of Fluent plugin

https://github.com/ryotarai/fluent-plugin-cloudwatch-logs

ref. https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/issues/69

## Do you want to add you to this organization?

Yes

**Comment by okkez** [comment]
@ryotarai Invited.
Could you transfer ownership to this organization?
And then add me to gem owner, please.

```
$ gem owner GEM -a okkez000@gmail.com
```

**Comment by ryotarai** [comment]
I'm very sorry but I decided to keep this repository as my project. Pull requests are welcome of course, and I'll handle existing pull requests and issues this week

**Comment by okkez** [comment]
OK. It's no problem.

**Comment by ryotarai** [comment]
I'm sorry but the situation changed and I would like nursery team to maintain fluent-plugin-cloudwatch-logs now. Would you please maintain this?

**Comment by okkez** [comment]
OK, we can take over fluent-plugin-cloudwatch-logs .

Could you transfer ownership to this organization?
And then add me to gem owner, please.

```
$ gem owner GEM -a okkez000@gmail.com
```

**Comment by ryotarai** [comment]
I've transferred it and add you to gem owners.

**Comment by okkez** [comment]
Thanks! I've confirmed.
