### ISSUE TITLE
fluent-plugin-zabbix-simple

### ISSUE THREAD

**Issue by sunny4381** [fluent-plugins-nursery/contact#5]
## Your repository URL of Fluent plugin

https://github.com/sunny4381/fluent-plugin-zabbix-simple

## Do you want to add you to this organization?

No

## Any question/concern?

No

**Comment by okkez** [comment]
I've invited you to this organization.
Could you transfer ownership to this organization.
And then could you add me to owner of gem.

```
$ gem owner GEM -a okkez000@gmail.com
```

**Comment by okkez** [comment]
@sunny4381 ping?

**Comment by sunny4381** [comment]
sorry for making you wait for a long time.
I'v done your request.

**Comment by okkez** [comment]
Thanks! I've confirmed gem owners.
