### ISSUE TITLE
mattheworiordan/fluent-plugin-color-stripper 

### ISSUE THREAD

**Issue by mattheworiordan** [fluent-plugins-nursery/contact#7]
Please input your Fluent plugin name to title.

## Your repository URL of Fluent plugin

https://github.com/mattheworiordan/fluent-plugin-color-stripper/issues/3

## Do you want to add you to this organization?

Yes

## Any question/concern?

Nope, let's do this :)  Thanks!

**Comment by okkez** [comment]
Thanks. I've invited you.

**Comment by okkez** [comment]
@mattheworiordan Could you transfer ownership https://github.com/mattheworiordan/fluent-plugin-color-stripper to this organization?

**Comment by scalp42** [comment]
@mattheworiordan any chance you can transfer ownership?

**Comment by kenhys** [comment]
@mattheworiordan Are you still want to transfer ownership? or I'll close this issue.
