### ISSUE TITLE
ento/fluent-plugin-out-http

### ISSUE THREAD

**Issue by ento** [fluent-plugins-nursery/contact#8]
Follow-up to https://github.com/ento/fluent-plugin-out-http/pull/23#issuecomment-432099814

## Your repository URL of Fluent plugin
https://github.com/ento/fluent-plugin-out-http

## Do you want to add you to this organization?
No, I don't think it's necessary, unless you mean for the sake of transferring ownership.

## Any question/concern?
No.

**Comment by ento** [comment]
I've initiated the ownership transfer (and looks like it's done).

Note: I selected all of the teams when GitHub prompted me to select which teams should have access to the transferred repo.

I also did the gem ownership step:

```
Owner added successfully.
Owners for gem: fluent-plugin-out-http
- okkez000@...
...
```

**Comment by ento** [comment]
The repo still has the `maintainer-wanted` label - you should take it off :) I don't seem to have the permission to remove it.

**Comment by cosmo0920** [comment]
Thank you so much! I've confirmed okkez become gem owners.
